"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](fg:current_line)\
$status\
$directory\
$golang\
$nodejs\
$python\
$rust\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$time\
$username\
$line_break\
$character\
"""

right_format = """
$line_break\
$aws\
$kubernetes\
"""

palette = 'catppuccin_mocha'
add_newline = true

[palettes.catppuccin_mocha]
foreground = '#D9E0EE'
background = '#1E1E2E'
current_line = '#2E2E3E'
primary = '#313244'
box = '#2E2E3E'
blue = '#8AADF4'
cyan = '#76E3F6'
green = '#A6E3A1'
orange = '#F9AF74'
pink = '#F5BDE6'
purple = '#CBA6F7'
red = '#F38BA8'
yellow = '#F9E2AF'
status = "#e23140"

[status]
format = '[─](fg:current_line)[](fg:status)[  ](fg:primary bg:status)[](fg:status bg:box)[ $status](fg:foreground bg:box)[](fg:box)'
pipestatus = true
pipestatus_separator = '-'
pipestatus_segment_format = '$status'
pipestatus_format = '[─](fg:current_line)[](fg:status)[  ](fg:primary bg:status)[](fg:status bg:box)[ $pipestatus](fg:foreground bg:box)[](fg:box)'

[directory]
format = '[─](fg:current_line)[](fg:pink)[ 󰷏 ](fg:primary bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = ' ~/'
truncation_symbol = ' '
truncation_length = 2
read_only = '󱧵 '
read_only_style = ''

[git_branch]
format = '[─](fg:current_line)[](fg:green)[ $symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)'

[git_status]
format = '[$all_status](fg:green bg:box)[](fg:box)'
conflicted = ' ='
up_to_date = ''
untracked = ' ?${count}'
stashed = ' $'
modified = ' !${count}'
staged = ' +'
renamed = ' »'
deleted = ' ✘'
ahead = ' ⇡${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
behind = ' ⇣${count}'

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' 󰎙 '

[rust]
format = '[─](fg:current_line)[](fg:red)[$symbol](fg:primary bg:red)[](fg:red bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '  '

[python]
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ (${version} )(\($virtualenv\) )](fg:foreground bg:box)[](fg:box)'
symbol = '  '

[golang]
format = '[─](fg:current_line)[](fg:cyan)[$symbol](fg:primary bg:cyan)[](fg:cyan bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = '  '

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:yellow)[  ](fg:primary bg:yellow)[](fg:yellow bg:box)[ $duration](fg:foreground bg:box)[](fg:box)'

[time]
format = '[─](fg:current_line)[](fg:purple)[ 󰥔 ](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'

[aws]
format = '(fg:current_line)[](fg:orange)[$symbol](fg:primary bg:orange)[](fg:orange bg:box)[ $profile](fg:foreground bg:box)[](fg:box)'
symbol = ' 󰸏 '
[aws.region_aliases]
us-east-1 = 'east'
us-west-2 = 'west'
[aws.profile_aliases]
DEV_PROFILE = 'Dev'
QA_PROFILE= 'QA'
PROD_PROFILE = 'Prod'

[kubernetes]
symbol = ' 󱃾 '
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ $cluster](fg:foreground bg:box)[](fg:box)'
disabled = false

