[[session]]
name = "tmux config"
path = "~/dotfiles/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/dotfiles/tmux/tmux.conf"

[[session]]
name = "nvim config"
path = "~/dotfiles/nvim"
startup_command = "nvim"
preview_command = "bat --color=always ~/dotfiles/nvim/init.lua"
