---
name: Test Dotfiles
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test-dotfiles:
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh {0}
    steps:
      - name: Set config paths
        run: |
          export ZDOTDIR="$HOME/.config/zsh"
          export XDG_CONFIG_HOME="$HOME/.config"
          echo "ZDOTDIR=$ZDOTDIR" >> $GITHUB_ENV
          echo "XDG_CONFIG_HOME=$XDG_CONFIG_HOME" >> $GITHUB_ENV
      - name: Confirm Zsh
        run: |
          echo "Zsh version: $(zsh --version)"
          echo "Current shell: $0"
          echo "Zsh test: [[ -o interactive ]] && echo interactive || echo non-interactive"
      - uses: actions/checkout@v4
      - name: Prepare environment
        run: |
          echo "SHELL = $SHELL"
          echo "ZDOTDIR = $ZDOTDIR"
          echo "XDG_CONFIG_HOME = $XDG_CONFIG_HOME"
          cp -r "$GITHUB_WORKSPACE" "$HOME"
          cd $HOME/dotfiles
      - name: Run full bootstrap
        working-directory: /Users/runner/dotfiles
        run: |
          make init
          source $XDG_CONFIG_HOME/zsh/.zshrc
          set -x
          ls -al $XDG_CONFIG_HOME
      - name: Validate core symlinks
        run: |
          # Validate symlinked directories
          test -L "$XDG_CONFIG_HOME/zsh" || { echo "❌ Missing symlink: .config/zsh"; exit 1; }
          test -L "$XDG_CONFIG_HOME/nvim" || { echo "❌ Missing symlink: .config/nvim"; exit 1; }
          test -L "$XDG_CONFIG_HOME/tmux" || { echo "❌ Missing symlink: .config/tmux"; exit 1; }

          # Validate critical config files
          test -e "$XDG_CONFIG_HOME/zsh/.zshrc"       || { echo "❌ Missing .zshrc in .config/zsh"; exit 1; }
          test -e "$XDG_CONFIG_HOME/nvim/init.lua"    || { echo "❌ Missing init.lua in .config/nvim"; exit 1; }
          test -e "$XDG_CONFIG_HOME/tmux/tmux.conf"    || { echo "❌ Missing init.lua in .config/tmux/"; exit 1; }
          echo "✅ All required symlinks and config files are present."
      - name: Show final structure
        run: |-
          tree -L 2 $XDG_CONFIG_HOME || true
