---
name: Test Dotfiles
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test-dotfiles:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dotfiles
      - name: Simulate real dotfiles install location
        run: |
          mv "$GITHUB_WORKSPACE/dotfiles" "$HOME"
          cd "$HOME/dotfiles"
      - name: Show environment
        run: |
          echo "HOME is: $HOME"
          echo "PWD is: $PWD"
      - name: Run full bootstrap
        working-directory: ${{ env.HOME }}/dotfiles
        run: make init
      - name: Validate core symlinks
        run: |
          test -L "$HOME/.zshrc" || (echo "Missing .zshrc symlink" && exit 1)
          test -L "$HOME/.config/nvim/init.lua" || (echo "Missing Neovim config" && exit 1)
      - name: Show final structure
        run: |-
          tree -L 2 "$HOME/.config" || true
